debug: false #??? ??? ??? ??? ? ? ? ??? ?? ??.(?? ??? ??????? false? ?? ??)
management.endpoints.web.exposure.include: "*" # actuator? endpoint? ??? ?? ??? ? ? ? ?? ?? (?? ???? ???? ??? ? ? ? ?? ??)

logging:
  level:
    com.com.bitstudy.app: debug #?? ????? ???? ?? ??? debug??? ??? ?? ?
    org.springframework.web.servlet: debug #? ?? ?? debug: false ? ?? ???. ?? true? ? ?? ?? ??? ??? ??? ??? ??. ??? ?? false? ?? request, response ??? ?? ??? ??? ?? ?.
    org.hibernate.type.descriptor.sql.BasicBinder: trace #JPA ??? ??? ? ?? ??? ??? ??? ??? ? ?? ??( ? ? ???? ?????? ? ???? ??. ?? ? ? ?? ??? ?)
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/board
    username: bitstudy
    password: whalestar0815
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    defer-datasource-initialization: true # test? ?????? ???? ??? ? ?? ??? ? .(??? data.sql??? ??? ???? ?? ??? ???? ? insert?? ?)
    hibernate.ddl-auto: create #???? ?? ??? ??? ???(??)? ???? ???? DDL???? ????.
                              # domain ? ?? Entity ???? ?? create table ?? ???? ???? ??? ? ???? ???? ??
    show-sql: true #??? ???? sql???? ??(true, false)
    properties:
      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 100
  h2.console.enabled: false
  sql.init.mode: always #? ??? ??? data.sql? ?? ?????? ???? ??
                        # never(????), always(?? ??), Embedded(??? ??)